apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'auth'
        metrics_path: /metrics
        static_configs:
          - targets: ['auth.default.svc.cluster.local:3000']

      - job_name: 'product'
        metrics_path: /metrics
        static_configs:
          - targets: ['product.default.svc.cluster.local:3000']

      - job_name: 'order'
        metrics_path: /metrics
        static_configs:
          - targets: ['order.default.svc.cluster.local:3000']

      - job_name: 'cart'
        metrics_path: /metrics
        static_configs:
          - targets: ['cart.default.svc.cluster.local:3000']

      - job_name: 'payment-blue'
        metrics_path: /metrics
        static_configs:
          - targets: ['payment-blue.default.svc.cluster.local:3000']

      - job_name: 'payment-green'
        metrics_path: /metrics
        static_configs:
          - targets: ['payment-green.default.svc.cluster.local:3000']

