apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'auth'
        static_configs:
          - targets: ['auth:3000']
      - job_name: 'product'
        static_configs:
          - targets: ['product:3000']
      - job_name: 'order'
        static_configs:
          - targets: ['order:3000']
      - job_name: 'cart'
        static_configs:
          - targets: ['cart:3000']
      - job_name: 'payment'
        static_configs:
          - targets: ['payment:3000']
