apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
      version: green
  template:
    metadata:
      labels:
        app: payment
        version: green
    spec:
      containers:
      - name: payment
        image: subin4123/payment
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"

