apiVersion: v1
kind: Service
metadata:
  name: payment-blue
spec:
  selector:
    app: payment
    version: blue
  ports:
    - protocol: TCP
      port: 80          # This is the service port (unchanged)
      targetPort: 3000  # This must match the container port inside the pod
        

