apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
      color: green
  template:
    metadata:
      labels:
        app: auth
        color: green
    spec:
      containers:
      - name: auth
        image: subin4123/auth:{{TAG}}
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"

