apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
      color: blue
  template:
    metadata:
      labels:
        app: auth
        color: blue
    spec:
      containers:
      - name: auth
        image: subin4123/auth:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"

