apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
      color: green
  template:
    metadata:
      labels:
        app: cart
        color: green
    spec:
      containers:
      - name: cart
        image: subin4123/cart:{{TAG}}
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

