apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
      version: green
  template:
    metadata:
      labels:
        app: cart
        version: green
    spec:
      containers:
      - name: cart
        image: subin4123/cart:v2
        ports:
        - containerPort: 3000

