apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
      version: blue
  template:
    metadata:
      labels:
        app: cart
        version: blue
    spec:
      containers:
      - name: cart
        image: subin4123/cart:{{TAG}}
        ports:
        - containerPort: 3000

