apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: your-dockerhub/cart
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
