apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
      color: blue
  template:
    metadata:
      labels:
        app: order
        color: blue
    spec:
      containers:
      - name: order
        image: subin4123/order:v1  # ✅ Make sure to push a blue version too!
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"

