apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: your-dockerhub/order
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
