apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
      color: blue
  template:
    metadata:
      labels:
        app: product
        color: blue
    spec:
      containers:
      - name: product
        image: subin4123/product:v2
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"

