apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: your-dockerhub/product
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
