apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: default
spec:
  selector:
    app: product
    color: blue  # default starting color
  ports:
    - port: 80
      targetPort: 3000

